Update build&test.yaml

diff --git a/.github/workflows/build&test.yaml b/.github/workflows/build&test.yaml
--- a/.github/workflows/build&test.yaml
+++ b/.github/workflows/build&test.yaml
@@ -9,6 +9,14 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
+    - name: Setup pipeline enforcer
+      uses: aquasecurity/pipeline-enforcer-action@main
+      env:
+        CSPM_URL: https://eu-1.api.cloudsploit.com
+        AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
+      with:
+        aqua-key: ${{ secrets.AQUA_KEY }}
+        aqua-secret: ${{ secrets.AQUA_SECRET }}
     - name: Build the Docker image
       run: | 
           docker build . --file Dockerfile --tag my-image-name:2024
@@ -32,11 +40,25 @@ jobs:
             # --artifact-path "my-image-name:${{ env.tag-version }}" 
             # OR the path to the root folder of your project. I.e my-repo/my-app 
             # --artifact-path "${{env.MY_APP_ROOT}}"
-    - name: Setup pipeline enforcer
-      uses: aquasecurity/pipeline-enforcer-action@main
-      env:
-        CSPM_URL: https://eu-1.api.cloudsploit.com
-        AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
-      with:
-        aqua-key: ${{ secrets.AQUA_KEY }}
-        aqua-secret: ${{ secrets.AQUA_SECRET }}
+    - name: Manifest Generation
+        run: |
+          export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum ; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate \
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --cspm-url https://eu-1.api.cloudsploit.com \
+            --artifact-path "my-image-name:${{ env.tag-version }}" 
+
+            # The docker image name:tag of the newly built image
+            # --artifact-path "my-image-name:${{ env.tag-version }}" 
+            # OR the path to the root folder of your project. I.e my-repo/my-app 
+            # --artifact-path "${{env.MY_APP_ROOT}}"
